# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecocase_title', models.CharField(max_length=200)),
                ('ecocase_description', models.TextField(max_length=300)),
                ('ecocase_characters', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ESM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm_title', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('ecocase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoCases.EcoCase')),
            ],
        ),
    ]
