# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoCases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='ecocase_characters',
            field=models.TextField(max_length=5000),
        ),
    ]
