# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0003_auto_20170920_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecocase',
            old_name='img_url_list',
            new_name='ecocase_images_urls',
        ),
    ]
