# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0005_auto_20170920_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='ecocase_images',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/ecocases/'), upload_to=''),
        ),
    ]
