# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0007_auto_20170920_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
