# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0009_ecocase_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='pub_date',
        ),
    ]
