# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0010_remove_ecocase_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
