# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0011_auto_20170920_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='ecocase_characters',
            field=tinymce.models.HTMLField(),
        ),
    ]
