# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0012_auto_20170920_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
