# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0014_auto_20170920_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='esm',
            name='esm_type',
            field=models.CharField(choices=[('esm01', 'ESM01'), ('esm02', 'ESM02'), ('esm03', 'ESM03'), ('esm04', 'ESM04'), ('esm05', 'ESM05'), ('esm06', 'ESM06'), ('esm07', 'ESM07'), ('esm08', 'ESM08')], default='ESM01', max_length=100),
        ),
    ]
