# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0016_auto_20170921_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esm',
            name='esm_type',
            field=models.CharField(choices=[('esm1', 'ESM1'), ('esm2', 'ESM2'), ('esm3', 'ESM3'), ('esm4', 'ESM4'), ('esm5', 'ESM5'), ('esm6', 'ESM6'), ('esm7', 'ESM7'), ('esm8', 'ESM8')], default='ESM01', max_length=100),
        ),
    ]
