# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0017_auto_20170921_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
